name: Round 3

on:
  push:
    branches: [round-3]

jobs: 
  grade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        fetch-depth: '0'
    - name: Setup Maven
      if: always()
      run: |
        sudo apt-get install default-jre
        sudo apt-get install default-jdk
        sudo apt-get install maven
    - name: Setup Python
      if: always()
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.6
    - name: Set up grading environment
      run: |
        sudo apt-get update
        sudo python -m pip install --upgrade pip
        sudo python -m pip install gatorgrade --ignore-installed PyYAML
    - name: Evaluate Round 1
      run: |
        cd 1
        gatorgrade --config gatorgrade.yml --report file json gatorgrade_summary.json
      if: always()
      env:   
        PIPENV_VENV_IN_PROJECT: 1
        PIPENV_IGNORE_VIRTUALENVS: 1
